deploy:
  provider: heroku
  api_key:
    secure: b68XfRrgUqoLTxAlgMNB0uredPj8YBZoC1ZDMckopCDnEQwc7zDY4u5hpgxG+m7iZxI3CsaYyy8CCyqng5iGzgOhNOrf0yF/FjQaKjbdHJkspFSPAyOYRjhaTpuAupWoRkStm4jyzgze1s91JkZ+JxuIoc34VdiR+SWGdl0iLCF4UmrUBVmm73FygtvEowbcR33AwiG3mQtpNIwZvWJWbHME3IAAmNgf58mLhb9horUzQxxp0kR/XgH+vmYEeeHLkGlhnYPTfQtglydmCMPploqCieETyNQK5fGhWISNx7zNEmKhAOvWmMhpS9yTwxCdZtK2S87ddwg7aZWY3sjAqEYZVie49wtNKDQjjpiUORWauoYtmqgqAT1JjODymyka+ZOiAI0W7Q7Clbv0IL+F7CXvcf0tL4erEqfHiOwABxNq3Q6utC8vpmzWcFAVgYTkUxmWFLOYStIeGhKr86dSewFQeb4GwzAnilfX6iQ9OZxlqAWsydbkJ97wTssABDZ0XpjH/ZYWjA1Ra8uGLxo7a9Ugs2/mKy7NPtTd2QIrowIlw4f4HHYFkZs/S6ggh9ZN+THY2UvZA4it8yGz12CiBeGfu83DA0clHdnNr3fQ62NO19KEUYN+7kBwH2zG4WEmz27BQg20JZqn7pWiuS5CLooYFUQXi91mKqcZmRdpm/k=
  app: node-integration-testing
  on:
    repo: mthinton/node-integration-testing
